config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"

  resources :events do
    resources :event_quotes do
      get :new_food, on: :collection
      get :new_costume, on: :collection
      get :new_beauty, on: :collection
      get :new_flower, on: :collection
      get :new_print, on: :collection
      get :new_staging, on: :collection
      get :new_photo, on: :collection
      get :new_video, on: :collection
      get :new_gift, on: :collection
      get :new_pre_ceremony, on: :collection
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :event_quotes, dependent: :destroy

  with_options presence: true do
    validates :name
    validates :event_date, format: { with: /\A\d{4}-\d{2}-\d{2}\z/ }
  end
end

app/models/event_form.rb
class EventForm
  include ActiveModel::Model

  # イベントフォームの属性を設定
  attr_accessor :event_id, :version_number, :detail, :cost, :input_date,
                :ceremony_type, :ceremony_cost,
                :adult_count, :child_count,
                :food_type, :food_cost,
                :venue_type, :venue_cost,
                :costume_type, :costume_cost,
                :beauty_type, :beauty_cost,
                :flower_type, :flower_cost,
                :print_type, :print_cost,
                :staging_type, :staging_detail, :staging_cost,
                :photo_type, :photo_cost,
                :video_type, :video_cost,
                :gift_type, :gift_cost,
                :pre_ceremony_type, :pre_ceremony_cost,
                :foods, :ceremonies, :venues, :costumes, :beauties, :flowers, :prints, :stagings, :photos, :videos, :gifts, :pre_ceremonies

  # バリデーションを設定
  validates :event_id, :version_number, :input_date,
            :adult_count, :child_count, presence: true
  validates :cost, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :adult_count, :child_count, numericality: { only_integer: true }
  validates :ceremony_cost, :food_cost, :venue_cost, :costume_cost, :beauty_cost, :flower_cost, :print_cost, :staging_cost,
            :photo_cost, :video_cost, :gift_cost, :pre_ceremony_cost, numericality: { only_integer: true, allow_blank: true }

  RELATED_ATTRIBUTES = {
    foods: Food,
    ceremonies: Ceremony,
    venues: Venue,
    costumes: Costume,
    beauties: Beauty,
    flowers: Flower,
    prints: Print,
    stagings: Staging,
    photos: Photo,
    videos: Video,
    gifts: Gift,
    pre_ceremonies: PreCeremony
    }.freeze
    
  def initialize(attributes = {})
    super attributes
    RELATED_ATTRIBUTES.each do |relation, model_class|
      instance_variable_set("@#{relation}", 10.times.map { model_class.new }) unless send(relation).present?
    end
  end

  RELATED_ATTRIBUTES.keys.each do |relation|
    define_method("#{relation}_attributes=") do |attributes|
      send("#{relation}=", attributes.map { |_, v| RELATED_ATTRIBUTES[relation].new(v) })
    end
  end
  # イベントフォームの保存メソッド
  def save
    # トランザクションを開始
    Event.transaction do
      # イベント見積もりを作成
      event_quote = EventQuote.create!(
        event_id: event_id,
        version_number: version_number,
        detail: detail,
        cost: cost,
        input_date: input_date
      )
      # ゲストを作成
      guest = Guest.create!(
        event_quote_id: event_quote.id,
        adult_count: adult_count,
        child_count: child_count
      )
      # 各属性のインスタンスを作成
      ceremonies.each do |ceremony|
        Ceremony.create!(
          event_quote_id: event_quote.id,
          ceremony_type: ceremony.ceremony_type,
          ceremony_cost: ceremony.ceremony_cost
        )
      end
      foods.each do |food|
        Food.create!(
          event_quote_id: event_quote.id,
          food_type: food.food_type,
          food_cost: food.food_cost
        )
      end
      venues.each do |venue|
        Venue.create!(
          event_quote_id: event_quote.id,
          venue_type: venue.venue_type,
          venue_cost: venue.venue_cost
        )
      end
      costumes.each do |costume|
        Costume.create!(
          event_quote_id: event_quote.id,
          costume_type: costume.costume_type,
          costume_cost: costume.costume_cost
        )
      end
      beauties.each do |beauty|
        Beauty.create!(
          event_quote_id: event_quote.id,
          beauty_type: beauty.beauty_type,
          beauty_cost: beauty.beauty_cost
        )
      end
      flowers.each do |flower|
        Flower.create!(
          event_quote_id: event_quote.id,
          flower_type: flower.flower_type,
          flower_cost: flower.flower_cost
        )
      end
      prints.each do |print|
        Print.create!(
          event_quote_id: event_quote.id,
          print_type: print.print_type,
          print_cost: print.print_cost
        )
      end
      stagings.each do |staging|
        Staging.create!(
          event_quote_id: event_quote.id,
          staging_type: staging.staging_type,
          staging_cost: staging.staging_cost
        )
      end
      photos.each do |photo|
        Photo.create!(
          event_quote_id: event_quote.id,
          photo_type: photo.photo_type,
          photo_cost: photo.photo_cost
        )
      end
      videos.each do |video|
        Video.create!(
          event_quote_id: event_quote.id,
          video_type: video.video_type,
          video_cost: video.video_cost
        )
      end
      gifts.each do |gift|
        Gift.create!(
          event_quote_id: event_quote.id,
          gift_type: gift.gift_type,
          gift_cost: gift.gift_cost
        )
      end
      pre_ceremonies.each do |pre_ceremony|
        PreCeremony.create!(
          event_quote_id: event_quote.id,
          pre_ceremony_type: pre_ceremony.pre_ceremony_type,
          pre_ceremony_cost: pre_ceremony.pre_ceremony_cost
        )
      end
    end
    true
  rescue StandardError => e
    # 例外が発生した場合、falseを返す
    false
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_event, only: [:edit, :update, :destroy, :show]

  def index
    @events = user_signed_in? ? current_user.events : []
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to new_event_event_quote_path(event_id: @event.id)
    else
      render :new
    end
  end

  def edit
    redirect_to root_path unless @event.user_id == current_user.id
  end

  def update
    if @event.update(event_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @events = user_signed_in? ? current_user.events : []
    @event_quotes = user_signed_in? ? EventQuote.where(event_id: current_user.events.pluck(:id)).group_by(&:event_id) : []
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.user_id == current_user.id
      @event.destroy
      redirect_to events_path
    else
      redirect_to events_path
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :event_date)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div id="event-form-container">
  <header id="event-form-header">

  </header>
  <div id="event-form-main">
    <h2 id="event-form-title">イベントの概要を編集</h2>
    
    <%= form_with model: @event, local: true  do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div id="new-event">
      <div class="event-name-label">
        イベント名
        <span class="required">必須</span>
      </div>
      <%= f.text_area :name, class:"event-name-input", id:"event-name", placeholder:"結婚式など", maxlength:"40" %>
      <div id="event-date-section">
        <div class="event-date-label">
          イベントの日
          <span class="required">必須</span>
        </div>
        <%= f.date_field :event_date, class:"event-date-input", id:"event-date" %>
      </div>
    </div>
    <%# 下部ボタン %>
    <div id="event-form-buttons">
      <%= f.submit "更新" ,class:"submit-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer id="event-form-footer">
  </footer>
</div>

app/views/events/index.html.erb
<%= render "shared/header" %>

<% if user_signed_in? %>
  <% if @events.empty? %>
    <div class='event-info'>
      <h3 class='event-name'>
        <%= "まだイベントが登録されていません" %><br>
        <%= "イベントを登録して見積を登録しましょう" %>
      </h3>
        <%= link_to 'イベント登録', new_event_path, class: "event-red-btn" %></li>
    </div>
  <% else %>
    <% @events.each do |event| %>
      <div class='event-info'>
        <h3 class='event-name'>
          <%= event.name %>
        </h3>
        <div class='event-date'>
          <%= event.event_date %>
        </div>
        <%= link_to 'イベント詳細', event_path(event), method: :get, class: "event-red-btn", data: { turbo: false } %>
        <%= link_to 'イベント編集', edit_event_path(event), method: :get, class: "event-red-btn" %>
        <%= link_to '削除', event_path(event), data: { turbo_method: :delete }, class:'event-destroy' %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <div class='event-info'>
    <h3 class='event-name'>
      <%= "会員登録／ログインしましょう" %>
    </h3>
    <%= link_to 'ログイン', new_user_session_path, class: "event-red-btn" %></li>
    <%= link_to '会員登録', new_user_registration_path, class: "event-red-btn" %></li>
  </div>
<% end %>

app/views/events/new.html.erb
<%= render "shared/header" %>

<div id="event-form-container">
  <header id="event-form-header">

  </header>
  <div id="event-form-main">
    <h2 id="event-form-title">イベントの概要を入力</h2>
    
    <%= form_with model: @event, local: true, html: { data: { turbo: "false" } } do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div id="new-event">
      <div class="event-name-label">
        イベント名
        <span class="required">必須</span>
      </div>
      <%= f.text_area :name, class:"event-name-input", id:"event-name", placeholder:"結婚式など", maxlength:"40" %>
      <div id="event-date-section">
        <div class="event-date-label">
          イベント開催日
          <span class="required">必須</span>
        </div>
        <%= f.date_field :event_date, class:"event-date-input", id:"event-date" %>
      </div>
    </div>
    <%# 下部ボタン %>
    <div id="event-form-buttons">
      <%= f.submit "詳細入力へ" ,class:"submit-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer id="event-form-footer">
  </footer>
</div>

app/views/events/show.html.erb
<%= render "shared/header" %>

<h1>イベント詳細画面</h1>

<div class="event-list">
    <div class="event-item">
      <% remaining_days = (@event.event_date - Date.today).to_i %>
      <p><%= @event.name %>まであと<%= remaining_days %>日</p> <!-- イベント名とイベントまでの残り日数を表示 -->
      <%= link_to '見積登録', new_event_event_quote_path(event_id: @event.id), method: :get, class: "event-red-btn", data: { turbo: false } %> <!-- 見積登録へのリンク -->
    </div>
    <% event_quotes = @event_quotes[@event.id] || [] %>
    <% if event_quotes.any? %>
      <% event_quote = event_quotes.first %>
      <% first_quote = event_quotes.first.cost.to_i %>
      <% last_quote = event_quotes.last.cost.to_i %>
      <% difference = last_quote - first_quote %>
      <div class='event-info'>
        <h3 class='event-name'>
          初回見積: <%= number_with_delimiter(first_quote) %>円 <!-- 初回見積額を表示 -->
          最新見積: <%= number_with_delimiter(last_quote) %>円 <!-- 最新見積額を表示 -->
          差分: <%= number_with_delimiter(difference) %>円 <!-- 初回と最新の見積額の差分を表示 -->
        </h3>
        <div class='event-date'>
          <%= event_quote.input_date.strftime("%Y年%m月%d日") %> <!-- 見積登録日を表示 -->
        </div>  
      </div>
      <canvas id="myChart_<%= @event.id %>"></canvas> <!-- グラフ表示エリア -->

      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
      <script>
      const data = <%= event_quotes.map { |quote| quote.cost.to_i }.to_json.html_safe %>; <!-- 見積額のデータ -->
      const labels = <%= (1..event_quotes.size).map { |i| "登録：#{i}回目" }.to_json.html_safe %>; <!-- ラベルデータ -->
      document.addEventListener('DOMContentLoaded', (event) => {
        const ctx = document.getElementById('myChart_<%= @event.id %>').getContext('2d');
        if (!ctx) {
          console.error('Canvas element not found!'); <!-- エラーメッセージ -->
          return;
        }

        const minData = Math.min(...data);
        const yMin = minData > 0 ? minData / 2 : 0;

        const myChart = new Chart(ctx, { <!-- グラフの設定 -->
          type: 'bar',
          data: {
            labels: labels,
            datasets: [{
              label: '金額',
              data: data,
              backgroundColor: [ <!-- 背景色の設定 -->
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
              ],
              borderColor: [ <!-- 枠線の色の設定 -->
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
              ],
              borderWidth: 1 <!-- 枠線の幅の設定 -->
            }]
          },
          options: {
            scales: {
              yAxes: [{
                ticks: {
                  beginAtZero: false,
                  min: yMin
                }
              }]
            }
          }
        });
      });
      </script>
    <% else %>
      <p>見積登録ボタンを押下して見積を登録しましょう</p>
    <% end %>
    <div class="event-quotes-list">
      <% @event.event_quotes.each_with_index do |quote, index| %>
        <div class="event-quote-item">
          <p>登録回数: <%= index + 1 %></p> <!-- 登録回数を表示 -->
          <p>登録日: <%= quote.input_date.strftime("%Y年%m月%d日") %></p> <!-- 登録日を表示 -->
          <p>金額: <%= number_with_delimiter(quote.cost.to_i) %>円</p> <!-- 金額を表示 -->
          <p>大人の人数: <%= quote.guest.adult_count %></p> <!-- 大人の人数を表示 -->
          <p>子供の人数: <%= quote.guest.child_count %></p> <!-- 子供の人数を表示 -->
          <p>コメント: <%= quote.detail.present? ? quote.detail : 'なし' %></p> <!-- コメントを表示、コメントがnullの場合は'なし'を表示 -->
          <%= link_to '削除', event_event_quote_path(@event, quote), class: 'event-destroy', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %> <!-- 削除ボタン -->
        </div>
      <% end %>
    </div>
</div>