config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"

  resources :events do
    resources :event_quotes do
      get :new_food, on: :collection
      get :new_costume, on: :collection
      get :new_beauty, on: :collection
      get :new_flower, on: :collection
      get :new_print, on: :collection
      get :new_staging, on: :collection
      get :new_photo, on: :collection
      get :new_video, on: :collection
      get :new_gift, on: :collection
      get :new_pre_ceremony, on: :collection
    end
  end
end

app/models/event_quote.rb
class EventQuote < ApplicationRecord
  belongs_to :event
  has_one :guest, dependent: :destroy
  has_many :ceremonies, dependent: :destroy
  has_many :foods, dependent: :destroy
  has_many :venues, dependent: :destroy
  has_many :costumes, dependent: :destroy
  has_many :beauties, dependent: :destroy
  has_many :flowers, dependent: :destroy
  has_many :prints, dependent: :destroy
  has_many :stagings, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :videos, dependent: :destroy
  has_many :gifts, dependent: :destroy
  has_many :pre_ceremonies, dependent: :destroy
end

app/controllers/event_quotes_controller.rb
class EventQuotesController < ApplicationController
  # ユーザーがログインしていない場合、index以外のアクションは実行できないようにする
  before_action :authenticate_user!, except: [:index]

  # イベント見積もりの一覧を表示するアクション
  def index
    # ログインしているユーザーのイベントを取得
    @events = user_signed_in? ? current_user.events : []
    # ログインしているユーザーのイベント見積もりを取得
    @event_quotes = user_signed_in? ? EventQuote.where(event_id: current_user.events.pluck(:id)).group_by(&:event_id) : []
  end

  # 新しいイベント見積もりを作成するアクション
  def new
    # パラメータからイベントを取得
    @event = Event.find(params[:event_id])
    # 新しいイベントフォームを作成
    @event_form = EventForm.new
    # 各フィールドのインデックスを初期化

  end

  # イベント見積もりをデータベースに保存するアクション
  def create
    # パラメータからイベントを取得
    @event = Event.find(params[:event_id])
    # 新しいイベントフォームを作成し、パラメータを設定
    @event_form = EventForm.new(event_quote_params)
    # イベントIDを設定
    @event_form.event_id = @event.id

    # 現在の日付をinput_dateに設定
    @event_form.input_date = Date.today

    # costがnullの場合、デフォルト値を設定
    @event_form.cost ||= 0

    # 既存のイベントバージョンの数をカウントし、1を加えてversion_numberに設定
    @event_form.version_number = EventQuote.where(event_id: @event.id).count + 1

    # フォームが有効な場合、保存してイベントページにリダイレクト
    if @event_form.valid?
      @event_form.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  # イベント見積もりを削除するアクション
  def destroy
    # パラメータからイベントとイベント見積もりを取得
    @event = Event.find(params[:event_id])
    @event_quote = @event.event_quotes.find(params[:id])
    # イベントのユーザーIDが現在のユーザーIDと一致する場合、イベント見積もりを削除
    if @event.user_id == current_user.id
      @event_quote.destroy
      redirect_to event_path(@event)
    else
      # 一致しない場合、イベントページにリダイレクト
      redirect_to event_path(@event)
    end
  end

  # 新しい食事を作成するアクション
  def new_food
    @event_form = EventForm.new
    @event_form.foods.build
    render partial: 'food', locals: { index: Time.now.to_i, f: @event_form }
  end

  # 新しい衣装を作成するアクション
  def new_costume
    @event_form = EventForm.new
    @event_form.costumes.build
    render partial: 'costume', locals: { index: Time.now.to_i, f: @event_form }
  end

  # 新しい会場を作成するアクション
  def new_venue
    @event_form = EventForm.new
    @event_form.venues.build
    render partial: 'venue', locals: { index: Time.now.to_i, f: @event_form }
  end

  # 新しい挙式を作成するアクション
  def new_ceremony
    @event_form = EventForm.new
    @event_form.ceremonies.build
    render partial: 'ceremony', locals: { index: Time.now.to_i, f: @event_form }
  end

  # 新しい美容を作成するアクション
  def new_beauty
    @event_form = EventForm.new
    @event_form.beauties.build
    render partial: 'beauty', locals: { index: Time.now.to_i, f: @event_form }
  end

  # 新しい花を作成するアクション
  def new_flower
    @event_form = EventForm.new
    @event_form.flowers.build
    render partial: 'flower', locals: { index: Time.now.to_i, f: @event_form }
  end

  # 新しい印刷物を作成するアクション
  def new_print
    @event_form = EventForm.new
    @event_form.prints.build
    render partial: 'print', locals: { index: Time.now.to_i, f: @event_form }
  end

  # 新しいステージングを作成するアクション
  def new_staging
    @event_form = EventForm.new
    @event_form.stagings.build
    render partial: 'staging', locals: { index: Time.now.to_i, f: @event_form }
  end

  # 新しい写真を作成するアクション
  def new_photo
    @event_form = EventForm.new
    @event_form.photos.build
    render partial: 'photo', locals: { index: Time.now.to_i, f: @event_form }
  end

  # 新しいビデオを作成するアクション
  def new_video
    @event_form = EventForm.new
    @event_form.videos.build
    render partial: 'video', locals: { index: Time.now.to_i, f: @event_form }
  end

  # 新しいギフトを作成するアクション
  def new_gift
    @event_form = EventForm.new
    @event_form.gifts.build
    render partial: 'gift', locals: { index: Time.now.to_i, f: @event_form }
  end

  # 新しい前挙式を作成するアクション
  def new_pre_ceremony
    @event_form = EventForm.new
    @event_form.pre_ceremonies.build
    render partial: 'pre_ceremony', locals: { index: Time.now.to_i, f: @event_form }
  end

  private

  # パラメータからイベントフォームのデータを取得するメソッド
  def event_quote_params
    params.require(:event_form).permit(
      :detail, :cost, :adult_count, :input_date, :child_count,
      ceremonies_attributes: [:id, :ceremony_type, :ceremony_cost],
      foods_attributes: [:id, :food_type, :food_cost],
      costumes_attributes: [:id, :costume_type, :costume_cost],
      beauties_attributes: [:id, :beauty_type, :beauty_cost],
      flowers_attributes: [:id, :flower_type, :flower_cost],
      venues_attributes: [:id, :venue_type, :venue_cost],
      prints_attributes: [:id, :print_type, :print_cost],
      stagings_attributes: [:id, :staging_type, :staging_cost],
      photos_attributes: [:id, :photo_type, :photo_cost],
      videos_attributes: [:id, :video_type, :video_cost],
      gifts_attributes: [:id, :gift_type, :gift_cost],
      pre_ceremonies_attributes: [:id, :pre_ceremony_type, :pre_ceremony_cost]
    ).merge(event_id: params[:event_id])
  end
end

app/helpers/event_quotes_helper.rb
module EventQuotesHelper
end

app/views/event_quotes/index.html.erb
<%= render "shared/header" %>

<h1>イベント見積グラフ</h1>

<div class="event-list">
  <% @events.each do |event| %>
    <div class="event-item">
      <% remaining_days = (event.event_date - Date.today).to_i %>
      <p><%= event.name %>まであと<%= remaining_days %>日</p>
      <%= link_to '見積登録', new_event_event_quote_path(event_id: event.id), method: :get, class: "event-red-btn" %>
    </div>
    <% event_quotes = @event_quotes[event.id] %>
    <% if event_quotes.any? %>
      <% event_quote = event_quotes.first %>
      <% first_quote = event_quotes.first.cost %>
      <% last_quote = event_quotes.last.cost %>
      <% difference = last_quote - first_quote %>
      <div class='event-info'>
        <h3 class='event-name'>
          初回見積: <%= number_with_delimiter(first_quote) %>円
          最新見積: <%= number_with_delimiter(last_quote) %>円
          差分: <%= number_with_delimiter(difference) %>円
        </h3>
        <div class='event-date'>
          <%= event_quote.input_date.strftime("%Y年%m月%d日") %>
        </div>
      </div>
    <% end %>

    <canvas id="myChart_<%= event.id %>"></canvas>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script>
    const data = <%= event_quotes.map(&:cost).to_json.html_safe %>;
    const labels = <%= (1..event_quotes.size).map { |i| "登録：#{i}回目" }.to_json.html_safe %>;
    document.addEventListener('DOMContentLoaded', (event) => {
    const ctx = document.getElementById('myChart_<%= event.id %>').getContext('2d');
    const myChart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: labels,
        datasets: [{
          label: labels,
          data: data,
          backgroundColor: [
            'rgba(255, 99, 132, 0.2)',
            'rgba(54, 162, 235, 0.2)',
            'rgba(255, 206, 86, 0.2)',
            'rgba(75, 192, 192, 0.2)',
            'rgba(153, 102, 255, 0.2)',
            'rgba(255, 159, 64, 0.2)'
          ],
          borderColor: [
            'rgba(255, 99, 132, 1)',
            'rgba(54, 162, 235, 1)',
            'rgba(255, 206, 86, 1)',
            'rgba(75, 192, 192, 1)',
            'rgba(153, 102, 255, 1)',
            'rgba(255, 159, 64, 1)'
          ],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
    });
    </script>
    <div class="event-quotes-list">
      <% event_quotes.each_with_index do |quote, index| %>
        <div class="event-quote-item">
          <p>登録回数: <%= index + 1 %></p>
          <p>登録日: <%= quote.input_date.strftime("%Y年%m月%d日") %></p>
          <p>金額: <%= number_with_delimiter(quote.cost) %>円</p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/event_quotes/new.html.erb
<%= render "shared/header" %>

<div id="event-form-container">
  <header id="event-form-header">
  </header>
  <div id="event-form-main">
    <h2 id="event-form-title">イベントの見積金額を入力</h2>
  </div>
    <%= form_with model: @event_form, url: event_event_quotes_path(@event), local: true, html: { data: { turbo: "false" } } do |f| %>
      <%= render 'shared/error_messages', model: @event_form %>
        
      <div id="new-event">

        <%# ゲスト %>
        <div class="event-name-label">
          ゲスト人数（大人）
        </div>
        <%= f.text_field :adult_count, class:"event-name-input", id:"adult_count-input", placeholder:"大人の参加人数を入力", maxlength:"40" %>
        <div class="event-name-label">
          ゲスト人数（子供）
        </div>
        <%= f.text_field :child_count, class:"event-name-input", id:"child_count-input", placeholder:"子供の参加人数を入力", maxlength:"40" %>

        <%# 挙式 %>
        <div class="event-name-label">
          挙式（挙式料／チャペル演出／フラワーシャワーなど）
        </div>
        <div id="ceremony-container">
          <% @event_form.ceremonies.each_with_index do |ceremony, index| %>
            <%= f.fields_for :ceremonies, ceremony do |i| %>
              <%= i.text_field "ceremony_type", class: "event-type-input", id: "ceremony_type_#{index + 1}", placeholder: "挙式の種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "ceremony_cost", class: "event-cost-input", id: "ceremony_cost_#{index + 1}", placeholder: "挙式のコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-ceremony-fields-button">+</button>

        <%# 料理 %>
        <div class="event-name-label">
          料理（料理（大人）／料理（子供）／飲料／ケーキなど）
        </div>
        <div id="food-container">
          <% @event_form.foods.each_with_index do |food, index| %>
            <%= f.fields_for :foods, food do |i| %>
              <%= i.text_field "food_type", class: "event-type-input", id: "food_type_#{index + 1}", placeholder: "料理の種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "food_cost", class: "event-cost-input", id: "food_cost_#{index + 1}", placeholder: "料理のコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-food-fields-button">+</button>
        
        <%# 会場 %>
        <div class="event-name-label">
          会場（会場使用料／ウェイティングルーム／メイクルームなど）
        </div>
        <div id="venue-container">
          <% @event_form.venues.each_with_index do |venue, index| %>
            <%= f.fields_for :venues, venue do |i| %>
              <%= i.text_field "venue_type", class: "event-type-input", id: "venue_type_#{index + 1}", placeholder: "会場の種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "venue_cost", class: "event-cost-input", id: "venue_cost_#{index + 1}", placeholder: "会場のコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-venue-fields-button">+</button>
        
        <%# 衣装 %>
        <div class="event-name-label">
          衣装（新郎衣装／新婦衣装／新婦小物など）
        </div>
        <div id="costume-container">
          <% @event_form.costumes.each_with_index do |costume, index| %>
            <%= f.fields_for :costumes, costume do |i| %>
              <%= i.text_field "costume_type", class: "event-type-input", id: "costume_type_#{index + 1}", placeholder: "衣装の種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "costume_cost", class: "event-cost-input", id: "costume_cost_#{index + 1}", placeholder: "衣装のコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-costume-fields-button">+</button>
        
        <%# 美容 %>
        <div class="event-name-label">
          美容（新婦支度料／新郎支度料／メイクリハーサルなど）
        </div>
        <div id="beauty-container">
          <% @event_form.beauties.each_with_index do |beauty, index| %>
            <%= f.fields_for :beauties, beauty do |i| %>
              <%= i.text_field "beauty_type", class: "event-type-input", id: "beauty_type_#{index + 1}", placeholder: "美容の種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "beauty_cost", class: "event-cost-input", id: "beauty_cost_#{index + 1}", placeholder: "美容のコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-beauty-fields-button">+</button>
        
        <%# 装花 %>
        <div class="event-name-label">
          装花（メインテーブル装花／ゲストテーブル装花／ブーケ・ブートニアなど）
        </div>
        <div id="flower-container">
          <% @event_form.flowers.each_with_index do |flower, index| %>
            <%= f.fields_for :flowers, flower do |i| %>
              <%= i.text_field "flower_type", class: "event-type-input", id: "flower_type_#{index + 1}", placeholder: "装花の種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "flower_cost", class: "event-cost-input", id: "flower_cost_#{index + 1}", placeholder: "装花のコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-flower-fields-button">+</button>
        
        <%# 印刷物 %>
        <div class="event-name-label">
          印刷物（招待状／席次表／席札など）
        </div>
        <div id="print-container">
          <% @event_form.prints.each_with_index do |print, index| %>
            <%= f.fields_for :prints, print do |i| %>
              <%= i.text_field "print_type", class: "event-type-input", id: "print_type_#{index + 1}", placeholder: "印刷物の種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "print_cost", class: "event-cost-input", id: "print_cost_#{index + 1}", placeholder: "印刷物のコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-print-fields-button">+</button>
        
        <%# 演出 %>
        <div class="event-name-label">
          演出（司会者/プロジェクションマッピング／著作権等使用料など）
        </div>
        <div id="staging-container">
          <% @event_form.stagings.each_with_index do |staging, index| %>
            <%= f.fields_for :stagings, staging do |i| %>
              <%= i.text_field "staging_type", class: "event-type-input", id: "staging_type_#{index + 1}", placeholder: "演出の種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "staging_cost", class: "event-cost-input", id: "staging_cost_#{index + 1}", placeholder: "演出のコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-staging-fields-button">+</button>
        
        <%# 写真 %>
        <div class="event-name-label">
          写真（スナップアルバムなど）
        </div>
        <div id="photo-container">
          <% @event_form.photos.each_with_index do |photo, index| %>
            <%= f.fields_for :photos, photo do |i| %>
              <%= i.text_field "photo_type", class: "event-type-input", id: "photo_type_#{index + 1}", placeholder: "写真の種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "photo_cost", class: "event-cost-input", id: "photo_cost_#{index + 1}", placeholder: "写真のコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-photo-fields-button">+</button>
        
        <%# ビデオ %>
        <div class="event-name-label">
          ビデオ（オープニングムービー／プロフィールムービー／エンドロールなど）
        </div>
        <div id="video-container">
          <% @event_form.videos.each_with_index do |video, index| %>
            <%= f.fields_for :videos, video do |i| %>
              <%= i.text_field "video_type", class: "event-type-input", id: "video_type_#{index + 1}", placeholder: "ビデオの種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "video_cost", class: "event-cost-input", id: "video_cost_#{index + 1}", placeholder: "ビデオのコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-video-fields-button">+</button>
        
        <%# 引出物 %>
        <div class="event-name-label">
          引出物（引出物／引菓子／ブライダルバックなど）
        </div>
        <div id="gift-container">
          <% @event_form.gifts.each_with_index do |gift, index| %>
            <%= f.fields_for :gifts, gift do |i| %>
              <%= i.text_field "gift_type", class: "event-type-input", id: "gift_type_#{index + 1}", placeholder: "引出物の種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "gift_cost", class: "event-cost-input", id: "gift_cost_#{index + 1}", placeholder: "引出物のコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-gift-fields-button">+</button>
        
        <%# 前撮り %>
        <div class="event-name-label">
          前撮り（新郎衣装／新婦衣装／新婦小物／新婦支度料／新郎支度料／新婦小物など）
        </div>
        <div id="pre_ceremony-container">
          <% @event_form.pre_ceremonies.each_with_index do |pre_ceremony, index| %>
            <%= f.fields_for :pre_ceremonies, pre_ceremony do |i| %>
              <%= i.text_field "pre_ceremony_type", class: "event-type-input", id: "pre_ceremony_type_#{index + 1}", placeholder: "前撮りの種類を入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
              <%= i.text_field "pre_ceremony_cost", class: "event-cost-input", id: "pre_ceremony_cost_#{index + 1}", placeholder: "前撮りのコストを入力", style: "display: #{index.zero? ? 'block' : 'none'};" %>
            <% end %>
          <% end %>
        </div>
        <button type="button" id="show-pre_ceremony-fields-button">+</button>
      </div>
      
      <div class="subtotal-display">
        小計: <span id="subtotal-display">0</span> 円
      </div>
      <div class="tax-amount-display">
        税額: <span id="tax-amount-display">0</span> 円
      </div>
      <div class="total-cost-display">
        税込価格: <span id="total-cost-display">0</span> 円
        <%= f.hidden_field :cost, id: "total-cost-hidden", value: 0 %>
      </div>
      
      <div class="event-detail-label">
        コメント
      </div>
      <%= f.text_area :detail, class: "event-detail-input", placeholder: "詳細を入力" %>

      <%# 下部ボタン %>
      <div id="event-form-buttons">
        <%= f.submit "登録" ,class:"submit-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
  <footer id="event-form-footer">
  </footer>
</div>


<script>
  window.onload = function() {
    var fieldIndices = {
      food: 1,
      venue: 1,
      ceremony: 1,
      gift: 1,
      pre_ceremony: 1,
      costume: 1,
      beauty: 1,
      flower: 1,
      print: 1,
      staging: 1,
      photo: 1,
      video: 1,
    };

    function showNextField(fieldType) {
      var index = fieldIndices[fieldType];
      var typeField = document.getElementById(fieldType + '_type_' + index);
      var costField = document.getElementById(fieldType + '_cost_' + index);
      if (typeField && costField) {
        typeField.style.display = 'block';
        costField.style.display = 'block';
        fieldIndices[fieldType]++;
      }
    }
    document.getElementById('show-ceremony-fields-button').addEventListener('click', function() {
      showNextField('ceremony');
    });

    document.getElementById('show-food-fields-button').addEventListener('click', function() {
      showNextField('food');
    });

    document.getElementById('show-venue-fields-button').addEventListener('click', function() {
      showNextField('venue');
    });

    document.getElementById('show-gift-fields-button').addEventListener('click', function() {
      showNextField('gift');
    });

    document.getElementById('show-pre_ceremony-fields-button').addEventListener('click', function() {
      showNextField('pre_ceremony');
    });

    document.getElementById('show-costume-fields-button').addEventListener('click', function() {
      showNextField('costume');
    });

    document.getElementById('show-beauty-fields-button').addEventListener('click', function() {
      showNextField('beauty');
    });

    document.getElementById('show-flower-fields-button').addEventListener('click', function() {
      showNextField('flower');
    });

    document.getElementById('show-print-fields-button').addEventListener('click', function() {
      showNextField('print');
    });

    document.getElementById('show-staging-fields-button').addEventListener('click', function() {
      showNextField('staging');
    });

    document.getElementById('show-photo-fields-button').addEventListener('click', function() {
      showNextField('photo');
    });

    document.getElementById('show-video-fields-button').addEventListener('click', function() {
      showNextField('video');
    });
  } 
</script>